GRANT SELECT, UPDATE, EXECUTE ON TC_MARKET TO danny;
GRANT SELECT, UPDATE, EXECUTE ON TC_PAIR TO danny;
GRANT SELECT, UPDATE, EXECUTE ON TB_USER_TRADE_FEE_DISCOUNT TO danny;
GRANT SELECT, UPDATE, EXECUTE ON TB_TRADE_FEE_UPDATE_HISTROY TO danny;
GRANT SELECT, UPDATE, EXECUTE ON  TO danny;
GRANT SELECT, UPDATE, EXECUTE ON  TO danny;
